import fs from 'fs';
import { dialog } from 'electron';

export class Exporter {
  public static async exportMarkdown(answers: string[], transcript: string[]) {
    const timestamp = new Date().toLocaleString();
    let content = `# 📝 Altus AI Interview Session Record\n`;
    content += `*Generated on: ${timestamp}*\n\n---\n\n`;

    content += `## 🎙️ Transcript History\n`;
    transcript.forEach((line, i) => {
      content += `> ${line}\n\n`;
    });

    content += `\n---\n\n## 💡 AI Technical Insights\n\n`;
    answers.forEach((answer, i) => {
      content += `### Answer ${i + 1}\n${answer}\n\n`;
    });

    content += `\n\n---\n*Confidential Document — Generated by Altus AI*`;

    const { filePath } = await dialog.showSaveDialog({
      title: 'Export Interview Session',
      defaultPath: `Altus_Interview_Export_${Date.now()}.md`,
      filters: [{ name: 'Markdown', extensions: ['md'] }]
    });

    if (filePath) {
      try {
        fs.writeFileSync(filePath, content, 'utf8');
        return true;
      } catch (err) {
        console.error('[Exporter] Failed to write file:', err);
        return false;
      }
    }
    return false;
  }
}
